# Generated by Django 4.2.4 on 2023-08-19 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='creation_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
